function createOrganizerWorkspaceSeed(sessionId) {
  return {
    sessionId,
    sessionLabel: "Истоки / Апрель 2026",
    title: "Личный кабинет организатора",
    summary: {
      activeEventLabel: "Лекция: дизайн сообщества",
      programsCount: 2,
      groupsCount: 3,
      speakersCount: 4,
      surveysCount: 3,
    },
    groupsSummary: {
      groups: [
        {
          id: "group-1",
          name: "Группа 1",
          curator: "Марина Чернова",
          participants: 18,
          avgActivation: 3.6,
          riskCases: 3,
          completion: 92,
          focus: "Сильный отклик на групповые форматы, просадка на логистике.",
        },
        {
          id: "group-2",
          name: "Группа 2",
          curator: "Даниил Крылов",
          participants: 21,
          avgActivation: 3.1,
          riskCases: 5,
          completion: 85,
          focus: "Нужна более ясная рамка практикумов и короткие паузы после переходов.",
        },
        {
          id: "group-3",
          name: "Группа 3",
          curator: "Елена Лисицына",
          participants: 17,
          avgActivation: 3.9,
          riskCases: 2,
          completion: 90,
          focus: "Высокая устойчивость, хорошо работают форматы с ясной ролью.",
        },
      ],
      alerts: [
        {
          id: "group-alert-1",
          severity: "high",
          title: "Практикум перегружает 2 группы из 3",
          detail: "После обеденного практикума у групп 1 и 2 фиксируются скачки и рост комментариев про шум и плотность.",
        },
        {
          id: "group-alert-2",
          severity: "medium",
          title: "Логистика просаживает активацию",
          detail: "Переходы без понятного маршрута дают среднюю потерю 1.1 пункта по шкале состояний.",
        },
      ],
    },
    sessionSummary: {
      keyStats: [
        { id: "stat-1", label: "Заполнение заезда", value: "89%" },
        { id: "stat-2", label: "Средняя активация", value: "3,5" },
        { id: "stat-3", label: "Резких переходов", value: "27" },
        { id: "stat-4", label: "Комментариев", value: "184" },
      ],
      eventHealth: [
        {
          id: "event-health-1",
          event: "Лекция: дизайн сообщества",
          format: "Лекция",
          speaker: "Анна Сорокина",
          effect: "+0.9 к среднему состоянию",
          concern: "Низкий риск",
          topTheme: "сильный спикер / вдохновение",
          recommendation: "Сохранять формат и длительность, оставить время на вопросы.",
        },
        {
          id: "event-health-2",
          event: "Практикум",
          format: "Мастерская",
          speaker: "Павел Демидов",
          effect: "+1.3 к вовлечённости",
          concern: "Высокий перегруз у 18% участников",
          topTheme: "слишком плотно / шумно",
          recommendation: "Развести потоки и добавить короткую тихую паузу после блока.",
        },
        {
          id: "event-health-3",
          event: "Переезд на площадку",
          format: "Логистика",
          speaker: "Операционный блок",
          effect: "-1.1 к среднему состоянию",
          concern: "Системная просадка",
          topTheme: "ожидание / непонятно что дальше",
          recommendation: "Давать маршрут заранее и закреплять ответственного модератора перехода.",
        },
      ],
      aiReports: [
        {
          id: "ai-report-1",
          title: "Итоги дня по заезду",
          confidence: "high",
          bullets: [
            "Смысловые форматы дали общий рост вовлечённости по всем группам.",
            "Основной риск дня - переходы и перегруженные мастерские без декомпрессии.",
            "Повторяющийся запрос участников: больше понятности, движения и коротких пауз.",
          ],
        },
        {
          id: "ai-report-2",
          title: "Рекомендации на завтра",
          confidence: "medium",
          bullets: [
            "Развести во времени интенсивные практикумы и логистику.",
            "Добавить тихий альтернативный контур вечером для чувствительных участников.",
            "Перед групповыми блоками коротко проговаривать цель и ожидаемый результат.",
          ],
        },
      ],
      typologies: [
        {
          id: "type-1",
          name: "Адаптивно-стабильный",
          share: 31,
          description: "Низкая амплитуда, уверенный баланс, устойчивость к смене форматов.",
        },
        {
          id: "type-2",
          name: "Социально-групповой ресурсный",
          share: 24,
          description: "Подъём на групповых форматах, чувствительность к логистике.",
        },
        {
          id: "type-3",
          name: "Эмоционально-чувствительный",
          share: 15,
          description: "Высокая реактивность к сенсорной нагрузке и плотному ритму.",
        },
      ],
    },
    speakerLectureSummary: {
      speakers: [
        {
          id: "speaker-1",
          name: "Анна Сорокина",
          role: "Спикер",
          topics: ["дизайн сообщества", "ценности"],
          eventsLed: 2,
          activationLift: "+0.9",
          feedbackTone: "сильный контентный эффект",
          recommendation: "Оставлять время на обсуждение после основного блока.",
        },
        {
          id: "speaker-2",
          name: "Павел Демидов",
          role: "Ведущий мастерских",
          topics: ["практикум", "фасилитация"],
          eventsLed: 3,
          activationLift: "+1.3",
          feedbackTone: "высокая вовлечённость и высокий перегруз",
          recommendation: "Декомпозировать задания и развести потоки по аудиториям.",
        },
        {
          id: "speaker-3",
          name: "Ирина Богданова",
          role: "Куратор рефлексии",
          topics: ["вечерняя свечка", "подведение итогов"],
          eventsLed: 2,
          activationLift: "+0.4",
          feedbackTone: "сильный стабилизирующий эффект",
          recommendation: "Сохранять как обязательную точку сборки дня.",
        },
      ],
      lectures: [
        {
          id: "lecture-1",
          title: "Лекция: дизайн сообщества",
          speakerName: "Анна Сорокина",
          day: "День 2",
          start: "10:00",
          end: "11:30",
          avgActivationDelta: "+0.9",
          completion: 96,
          topThemes: ["вдохновение", "понятная рамка", "сильный спикер"],
          note: "Лучший лекционный блок заезда по балансу качества и удержания внимания.",
        },
        {
          id: "lecture-2",
          title: "Открытый микрофон",
          speakerName: "Ирина Богданова",
          day: "День 2",
          start: "19:15",
          end: "20:30",
          avgActivationDelta: "+0.3",
          completion: 78,
          topThemes: ["самовыражение", "безопасное пространство"],
          note: "Сильный формат для рефлексивной части, но нуждается в точной фасилитации.",
        },
      ],
    },
    audiencePool: [
      {
        id: "participant-1",
        fullName: "Попов Иван Дмитриевич",
        groupId: "group-1",
        groupLabel: "Группа 1",
        age: 19,
        gender: "мужской",
        emotionalProfile: "социально-групповой ресурсный",
        identityStatus: "searching moratorium",
      },
      {
        id: "participant-2",
        fullName: "Сергеева Анна Павловна",
        groupId: "group-1",
        groupLabel: "Группа 1",
        age: 19,
        gender: "женский",
        emotionalProfile: "смысло-рефлексивный",
        identityStatus: "moratorium",
      },
      {
        id: "participant-3",
        fullName: "Кузнецов Егор Дмитриевич",
        groupId: "group-1",
        groupLabel: "Группа 1",
        age: 18,
        gender: "мужской",
        emotionalProfile: "эмоционально-чувствительный",
        identityStatus: "troubled diffusion",
      },
      {
        id: "participant-4",
        fullName: "Лисина Дарья Олеговна",
        groupId: "group-2",
        groupLabel: "Группа 2",
        age: 21,
        gender: "женский",
        emotionalProfile: "адаптивно-стабильный",
        identityStatus: "foreclosure",
      },
      {
        id: "participant-5",
        fullName: "Гаврилов Матвей Сергеевич",
        groupId: "group-2",
        groupLabel: "Группа 2",
        age: 17,
        gender: "мужской",
        emotionalProfile: "эмоционально-чувствительный",
        identityStatus: "carefree diffusion",
      },
      {
        id: "participant-6",
        fullName: "Федотова Мария Игоревна",
        groupId: "group-3",
        groupLabel: "Группа 3",
        age: 22,
        gender: "женский",
        emotionalProfile: "социально-групповой ресурсный",
        identityStatus: "achievement",
      },
    ],
    programWorkspace: {
      currentProgramId: "program-core",
      activeEventId: "event-d2-lecture",
      programs: [
        {
          id: "program-core",
          title: "Основная программа",
          status: "published",
          description:
            "Ключевая канва заезда: общие события, практикумы и обязательные точки синхронизации.",
          days: [
            {
              id: "day-1",
              label: "День 1",
              dateLabel: "24 апреля",
              events: [
                {
                  id: "event-d1-start",
                  title: "Утренний сбор",
                  start: "09:00",
                  end: "09:45",
                  type: "Открытый диалог",
                  speakerName: "Команда кураторов",
                  location: "Большой зал",
                  track: "Общий поток",
                  parallelGroup: "A",
                  status: "completed",
                  tags: ["ритуал", "включение"],
                  description: "Мягкий старт и настройка на ритм дня.",
                },
                {
                  id: "event-d1-trip",
                  title: "Экскурсия",
                  start: "10:00",
                  end: "12:00",
                  type: "Выездная программа",
                  speakerName: "Операционный блок",
                  location: "Маршрут 1",
                  track: "Общий поток",
                  parallelGroup: "A",
                  status: "completed",
                  tags: ["контекст", "движение"],
                  description: "Погружение в контекст форума вне аудитории.",
                },
              ],
            },
            {
              id: "day-2",
              label: "День 2",
              dateLabel: "25 апреля",
              events: [
                {
                  id: "event-d2-start",
                  title: "Утренний сбор",
                  start: "09:00",
                  end: "09:45",
                  type: "Открытый диалог",
                  speakerName: "Марина Чернова",
                  location: "Большой зал",
                  track: "Общий поток",
                  parallelGroup: "A",
                  status: "completed",
                  tags: ["ритуал", "включение"],
                  description: "Сверка состояния и настройка на насыщенный день.",
                },
                {
                  id: "event-d2-lecture",
                  title: "Лекция: дизайн сообщества",
                  start: "10:00",
                  end: "11:30",
                  type: "Лекция",
                  speakerName: "Анна Сорокина",
                  location: "Большой зал",
                  track: "Общий поток",
                  parallelGroup: "A",
                  status: "active",
                  tags: ["смыслы", "спикер"],
                  description: "Сильный контентный блок, сейчас выбран как актуальное событие.",
                },
                {
                  id: "event-d2-group",
                  title: "Групповая работа",
                  start: "12:00",
                  end: "13:00",
                  type: "Групповая",
                  speakerName: "Команда кураторов",
                  location: "Коворкинг 2",
                  track: "Общий поток",
                  parallelGroup: "A",
                  status: "planned",
                  tags: ["обсуждение", "команда"],
                  description: "Работа малыми группами по материалу лекции.",
                },
                {
                  id: "event-d2-workshop-a",
                  title: "Мастерская A: медиа и нарратив",
                  start: "14:00",
                  end: "15:30",
                  type: "Практикум",
                  speakerName: "Павел Демидов",
                  location: "Аудитория 5",
                  track: "Поток A",
                  parallelGroup: "P1",
                  status: "planned",
                  tags: ["параллель", "медиа"],
                  description: "Параллельная мастерская по работе с нарративами.",
                },
                {
                  id: "event-d2-workshop-b",
                  title: "Мастерская B: фасилитация группы",
                  start: "14:00",
                  end: "15:30",
                  type: "Практикум",
                  speakerName: "Павел Демидов",
                  location: "Аудитория 6",
                  track: "Поток B",
                  parallelGroup: "P1",
                  status: "planned",
                  tags: ["параллель", "фасилитация"],
                  description: "Параллельный трек по групповым инструментам.",
                },
              ],
            },
          ],
        },
        {
          id: "program-evening",
          title: "Вечерняя программа",
          status: "published",
          description:
            "Рефлексивные и неформальные форматы с возможностью тихих альтернатив.",
          days: [
            {
              id: "day-1",
              label: "День 1",
              dateLabel: "24 апреля",
              events: [
                {
                  id: "event-e1-campfire",
                  title: "Вечерняя свечка",
                  start: "19:00",
                  end: "20:15",
                  type: "Рефлексия",
                  speakerName: "Ирина Богданова",
                  location: "Каминный зал",
                  track: "Общий поток",
                  parallelGroup: "B",
                  status: "completed",
                  tags: ["рефлексия", "группа"],
                  description: "Основной вечерний формат сборки дня.",
                },
                {
                  id: "event-e1-quiet",
                  title: "Тихая зона восстановления",
                  start: "19:00",
                  end: "20:15",
                  type: "Поддержка",
                  speakerName: "Психологическая служба",
                  location: "Библиотека",
                  track: "Тихий контур",
                  parallelGroup: "B",
                  status: "completed",
                  tags: ["сенсорная разгрузка", "альтернатива"],
                  description: "Тихая параллель для участников, которым нужен щадящий режим.",
                },
              ],
            },
          ],
        },
      ],
    },
    surveyWorkspace: {
      filterOptions: {
        genders: ["мужской", "женский"],
        emotionalProfiles: [
          "адаптивно-стабильный",
          "социально-групповой ресурсный",
          "смысло-рефлексивный",
          "эмоционально-чувствительный",
          "саморегулирующийся",
        ],
        groupIds: ["group-1", "group-2", "group-3"],
      },
      surveys: [
        {
          id: "survey-identity-status",
          title: "Стартовый опрос по статусу идентичности",
          category: "Стартовый скрининг",
          cadence: "однократно в начале заезда",
          source:
            "Адаптировано по мотивам статей Becht et al. (2021) и Hatano et al. (2022).",
          description:
            "Черновой опрос для оценки commitment, exploration и reconsideration перед стартом программы.",
          status: "draft",
          questions: [
            {
              id: "survey-identity-status-q1",
              type: "scale",
              title: "У меня уже есть достаточно ясное представление о своих целях и ценностях.",
              options: ["1", "2", "3", "4", "5", "6"],
            },
            {
              id: "survey-identity-status-q2",
              type: "scale",
              title: "Сейчас я активно исследую разные варианты будущего и ролей для себя.",
              options: ["1", "2", "3", "4", "5", "6"],
            },
            {
              id: "survey-identity-status-q3",
              type: "scale",
              title: "Я часто пересматриваю уже принятые решения о себе и своём пути.",
              options: ["1", "2", "3", "4", "5", "6"],
            },
          ],
        },
        {
          id: "survey-identity-fluctuation",
          title: "Ежедневный опрос по флуктуациям идентичности",
          category: "Ежедневный pulse",
          cadence: "ежедневно вечером",
          source:
            "Адаптировано по мотивам daily identity processes из Hatano et al. (2022).",
          description:
            "Короткий pulse для отслеживания ежедневных колебаний в ясности, исследовании и пересмотре себя.",
          status: "published",
          questions: [
            {
              id: "survey-identity-fluctuation-q1",
              type: "scale",
              title: "Сегодня у меня было ясное ощущение, кто я и к чему иду.",
              options: ["1", "2", "3", "4", "5"],
            },
            {
              id: "survey-identity-fluctuation-q2",
              type: "scale",
              title: "Сегодня я активно пробовал(а) понять, какая роль или направление мне ближе.",
              options: ["1", "2", "3", "4", "5"],
            },
            {
              id: "survey-identity-fluctuation-q3",
              type: "single",
              title: "Какая зона самоопределения сегодня была самой чувствительной?",
              options: [
                "роль в группе",
                "учёба / профессия",
                "личные ценности",
                "отношения",
              ],
            },
          ],
        },
        {
          id: "survey-disc-team-role",
          title: "Командная роль по мотивам DISC",
          category: "Командное взаимодействие",
          cadence: "по решению организатора",
          source:
            "Прототипический конструктор по мотивам DISC для распределения ролей в команде, без претензии на психометрическую валидность.",
          description:
            "Опросник для рабочей гипотезы о стиле участия в команде: драйв, влияние, стабильность, системность.",
          status: "draft",
          questions: [
            {
              id: "survey-disc-team-role-q1",
              type: "single",
              title: "В новой группе я чаще всего...",
              options: [
                "быстро беру лидерство",
                "вовлекаю и зажигаю других",
                "поддерживаю устойчивость и атмосферу",
                "структурирую и навожу порядок",
              ],
            },
            {
              id: "survey-disc-team-role-q2",
              type: "single",
              title: "Когда команда буксует, я скорее...",
              options: [
                "давлю на решение",
                "убеждаю и двигаю эмоционально",
                "снижаю напряжение и удерживаю контакт",
                "возвращаю всех к логике и плану",
              ],
            },
          ],
        },
      ],
      publications: [
        {
          id: "publication-1",
          surveyId: "survey-identity-fluctuation",
          status: "active",
          publishedAt: "2026-04-25 08:30",
          audienceSummary: "Заезд 3 · 17–22 лет · все группы · все эмоциональные профили",
          recipientsCount: 6,
          filters: {
            ageMin: 17,
            ageMax: 22,
            genders: [],
            emotionalProfiles: [],
            groupIds: [],
          },
        },
      ],
    },
  };
}

module.exports = {
  createOrganizerWorkspaceSeed,
};
