"use strict";

/**
 * Phase F of «Истоки v2»: public-side content submissions + moderation queue.
 *
 * Anonymous visitors propose new podcasts / stories / chronicle entries
 * for a region; an admin reviews them in the moderation queue and either
 * approves (which copies the draft into the live istoki_* tables) or
 * rejects with a note.
 *
 * Single table `istoki_submissions` carries all three kinds — the type
 * is in `kind`, and the type-specific fields live in `draft_payload`
 * (jsonb), validated server-side by a Zod discriminated union.
 *
 * `status_token` is a base64url-encoded random string generated by the
 * application on insert. It's the only thing the submitter needs to
 * check the status of their submission via /istoki/submission/:token.
 */

exports.up = async (pgm) => {
  pgm.sql(`
    CREATE TABLE IF NOT EXISTS istoki_submissions (
      id                  text PRIMARY KEY,
      kind                text NOT NULL,
      region_code         text REFERENCES istoki_regions(code) ON DELETE SET NULL,
      status              text NOT NULL DEFAULT 'pending',
      submitter_name      text NOT NULL,
      submitter_email     text NOT NULL,
      draft_payload       jsonb NOT NULL DEFAULT '{}'::jsonb,
      moderation_note     text,
      reviewed_at         timestamptz,
      reviewed_by_user_id text REFERENCES users(id) ON DELETE SET NULL,
      status_token        text UNIQUE NOT NULL,
      created_at          timestamptz NOT NULL DEFAULT now(),
      updated_at          timestamptz NOT NULL DEFAULT now()
    );

    CREATE INDEX IF NOT EXISTS idx_istoki_submissions_status
      ON istoki_submissions(status, created_at DESC);
    CREATE INDEX IF NOT EXISTS idx_istoki_submissions_region
      ON istoki_submissions(region_code, created_at DESC);
  `);
};

exports.down = async (pgm) => {
  pgm.sql(`DROP TABLE IF EXISTS istoki_submissions;`);
};
